/* 
 This source code (the "Generated Software") is generated by the OutSystems Platform 
 and is licensed by OutSystems (http://www.outsystems.com) to You solely for testing and evaluation 
 purposes, unless You and OutSystems have executed a specific agreement covering the use terms and 
 conditions of the Generated Software, in which case such agreement shall apply. 
*/

using System;
using System.Text.RegularExpressions;
using OutSystems.HubEdition.Extensibility.Data;
using OutSystems.HubEdition.Extensibility.Data.DatabaseObjects;

using SnowflakeDatabaseProvider.Configuration;

namespace SnowflakeDatabaseProvider.Introspection {

    /// <summary>
    /// Creates introspection objects from qualified names, inspecting the database only if needed.
    /// </summary>
    public class SnowflakeDatabaseObjectFactory : IDatabaseObjectFactory {

        private static readonly Regex pieceRegex = new Regex("([^\\.`]+)", RegexOptions.Compiled);
        protected readonly IDatabaseServices databaseServices;

        /// <summary>
        /// Initializes a new instance of the <see cref="DatabaseObjectFactory"/> class.
        /// </summary>
        /// <param name="databaseServices">The database services.</param>
        public SnowflakeDatabaseObjectFactory(IDatabaseServices databaseServices)
        {
            this.databaseServices = databaseServices;
        }

        /// <summary>
        /// Returns an object that contains information about the current database
        /// </summary>
        /// <returns>
        /// Database-specific object that implements the IDatabaseInfo interface
        /// </returns>
        public IDatabaseInfo CreateLocalDatabaseInfo() {
            return new SnowflakeDatabaseInfo(databaseServices, null);
        }

        /// <summary>
        /// Returns an object that contains information about a database, inferring it from a database identifier.
        /// If the <paramref name="databaseIdentifier" /> does not contain all the required information, the remaining
        /// should be inferred from the current <see cref="T:OutSystems.HubEdition.Extensibility.Data.ConfigurationService.IRuntimeDatabaseConfiguration" />.
        /// </summary>
        /// <param name="databaseIdentifier">Unique identifier of the database</param>
        /// <returns>
        /// Database-specific object that implements the IDatabaseInfo interface
        /// </returns>
        public IDatabaseInfo CreateDatabaseInfo(string databaseIdentifier) {
            return new SnowflakeDatabaseInfo(databaseServices, databaseIdentifier);
        }

        /// <summary>
        /// Returns an object that contains information about a table source (data source in tabular format), like a database table or view,
        /// inferring both the database and table source information from a qualifiedName. If the <paramref name="qualifiedName" /> does not contain
        /// all the required information, the remaining should be inferred from the current <see cref="T:OutSystems.HubEdition.Extensibility.Data.ConfigurationService.IRuntimeDatabaseConfiguration" />.
        /// </summary>
        /// <param name="qualifiedName">Qualified identifier of the table source, including the database information</param>
        /// <returns>
        /// Database-specific object that implements the ITableSourceInfo interface
        /// </returns>
        public ITableSourceInfo CreateTableSourceInfo(string qualifiedName) {
            string table;
            string schema;
            string database;

            if (ParseQualifiedTableName(qualifiedName, out database, out schema, out table))
            {
                return new SnowflakeTableSourceInfo(databaseServices, new SnowflakeDatabaseInfo(databaseServices, schema), table, qualifiedName);
            }
            throw new Exception("'" + qualifiedName + "' is not a valid qualified table name.");
        }

        public static bool ParseQualifiedTableName(string qualifiedName, out string database, out string schema, out string table)
        {
            schema = "";
            table = "";
            database = "";

            MatchCollection matches = pieceRegex.Matches(qualifiedName);
            switch (matches.Count)
            {
                case 3:
                    database = matches[0].Value.Trim();
                    schema = matches[1].Value.Trim();
                    table = matches[2].Value.Trim();
                    break;
                case 2:
                    schema = matches[0].Value.Trim();
                    table = matches[1].Value.Trim();
                    break;
                case 1:
                    table = matches[0].Value.Trim();
                    break;
                default:
                    return false;
            }
            return true;
        }
    }
}
